### ISSUE TITLE
New Concept: [technosignatures]

### ISSUE THREAD

**Issue by astrowright** [astrothesaurus/UAT#290] opened 2019-10-14 00:50 UTC
Technosignatures 

**Describe the concept**
Best description is here:
https://arxiv.org/abs/1809.06857
From that work:
Any sign of technology that is not also a biosignature (i.e. that is not also a sign or
byproduct of metabolism in common with non-technological species).
Notes: By analogy with biosignature, technosignature refers to signs or signals, which, if
observed, would allow us to infer the existence of technological life elsewhere in the
universe; this tracks the natural meaning of the word and the intent of its original
coinage (see Tarter (2007) Highlights of Astronomy 14, 14). In some cases, the line
between biosignatures and technosignatures may be unclear, and technology need not
be of biological origin, as in the case of “postbiological evolution.”

**Describe where the concept fits within the existing hierarchy**
It could be considered a subset of astrobiology. Others would consider it distinct.

**Provide 1-3 supporting articles**
List bibcodes or other identifiers for articles that support the need for this new concept in the literature.
2018arXiv180906857W
2018arXiv181208681T
2007HiA....14...14T

**Please include any additional comments/feedback**
Heavy overlap if not outright synonymy with the old keyword "extraterrestrial intelligence."

**Comment by katieefrey** [comment] 2019-10-14 06:09
duplicate of #269 

I haven't mentioned it there yet, but this concept will be in the next release.

**Closed by katieefrey** 2019-10-14 06:09 UTC
Labels: add concept
